---
- name: Install Java
  apt:
    name: openjdk-11-jdk
    state: present

- name: Add Jenkins Debian repository key
  apt_key:
    url: https://pkg.jenkins.io/debian/jenkins.io.key
    state: present

- name: Add Jenkins Debian repository
  apt_repository:
    repo: deb http://pkg.jenkins.io/debian-stable binary/
    state: present

- name: Install Jenkins
  apt:
    name: jenkins
    state: present
    update_cache: yes

- name: Start and enable Jenkins service
  service:
    name: jenkins
    state: started
    enabled: true
